services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Mediapool\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Form/Element/*'

  qb.playlist:
    class: TYPO3\CMS\Core\Database\Query\QueryBuilder
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['tx_mediapool_domain_model_playlist']

  qb.video:
    class: TYPO3\CMS\Core\Database\Query\QueryBuilder
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['tx_mediapool_domain_model_video']

  JWeiland\Mediapool\Command\UpdatePlaylistInformationCommand:
    tags:
      - name: console.command
        command: 'mediapool:update:playlists'
        description: 'This task updates the playlist information'
        schedulable: true

  JWeiland\Mediapool\Command\UpdateVideoInformationCommand:
    tags:
      - name: console.command
        command: 'mediapool:update:videos'
        description: 'This task updates the video information'
        schedulable: true

  # Called by makeInstance in DataHandler
  JWeiland\Mediapool\Hook\DataHandlerHook:
    public: true

  JWeiland\Mediapool\Import\Playlist\YoutubePlaylistImport:
    tags:
      - name: 'mediapool.importer.playlist'

  JWeiland\Mediapool\Import\Video\YouTubeVideoImport:
    tags:
      - name: 'mediapool.importer.video'

  JWeiland\Mediapool\Service\Record\PlaylistRecordService:
    arguments:
      $queryBuilder: '@qb.playlist'

  JWeiland\Mediapool\Service\Record\VideoRecordService:
    arguments:
      $queryBuilder: '@qb.video'

  # Called by makeInstance in VideoLinkElement
  JWeiland\Mediapool\Service\ImportService:
    public: true
    arguments:
      $playlistImporters: !tagged_iterator { tag: 'mediapool.importer.playlist' }
      $videoImporters: !tagged_iterator { tag: 'mediapool.importer.video' }

  JWeiland\Mediapool\Service\PlaylistService:
    arguments:
      $importers: !tagged_iterator { tag: 'mediapool.importer.playlist' }

  JWeiland\Mediapool\Service\VideoService:
    arguments:
      $importers: !tagged_iterator { tag: 'mediapool.importer.video' }

  # Called by makeInstance in UpgradeWizardListCommand of EXT:install
  JWeiland\Mediapool\Updates\PlaylistSlugUpdate:
    public: true

  # Called by makeInstance in UpgradeWizardListCommand of EXT:install
  JWeiland\Mediapool\Updates\VideoSlugUpdate:
    public: true
